- name: This playbook will install nginx, configure nginx web root folder and deploys custom web page
  hosts: all
  tasks:
  - include_tasks: install-nginx-{{ansible_distribution|lower}}.yml
  - include_tasks: "start-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: common-nginx-tasks.yml
  - include_tasks: "configure-nginx-{{ansible_distribution|lower}}.yml"
  - include_tasks: "restart-nginx-{{ansible_distribution|lower}}.yml"
