- name: Configure nginx web server to serve web pages from our custom folder in Rocky ansible node
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - Restart the nginx service to apply the config changes in Rocky ansible node

