- name: Configure nginx web server to serve web pages from our custom folder in Ubuntu ansible node
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
  - Restart the nginx service to apply the config changes in Ubuntu ansible node
