- name: Check if nginx server is already running in Rocky ansible node
  shell: curl localhost:80
  register: output
  ignore_errors: yes

- name: Start the nginx service in Rocky ansible node
  when: output.rc != 0
  shell: nginx
